import { Readable } from "stream";
import cloudinary from "../config/cloudinary.js";

export const uploadBufferToCloudinary = (fileBuffer) => {
  return new Promise((resolve, reject) => {
    const uploadStream = cloudinary.uploader.upload_stream(
      { folder: "car_rental_uploads" },
      (error, result) => {
        if (error) return reject(error);
        resolve(result.secure_url); // This returns the secure URL automatically generated by Cloudinary
      }
    );
    Readable.from(fileBuffer).pipe(uploadStream);
  });
};
